### ISSUE TITLE
add document for build app

### ISSUE THREAD

**Issue by tnclong** [qor/bindatafs#3]
When you launch you app to live site, you should build with `-tags 'bindatafs'`.

```
go build -tags 'bindatafs' -o app main.go

./app

```

We only find document:

> If you started your application with tag bindatafs, AssetFS will access file from generated go file or current binary
> go run -tags 'bindatafs' main.go
> Or it will access its content from registered view paths of your filesystem, which is easier for your local development
> go run main.go

**Comment by coezbek** [comment]
I think @tnclong brings up two points:

- The documentation for bindatafs is not self explanatory at the moment. The examples should in particular give more details regarding file names of the given samples.

- The use of the tag 'bindatafs' is a really bad choice, because the default is not to use the cached files bindatafs, but access through the file system directly. Thus if you forget to add the parameter during a deploy build, then you forgetting your assets. I think compiling with 'bindatafs' should be the default.
